reporting-disabled = true
bind-address = "127.0.0.1:8088"

[meta]
  dir = "/data/influxdb/meta"

[data]
  dir = "/data/influxdb/data"
  wal-dir = "/data/influxdb/wal"
  query-log-enabled = false

[http]
  enabled = true
  bind-address = ":8086"
  auth-enabled = true
  log-enabled = false
  flux-enabled = false
  pprof-enabled = false
  ping-auth-enabled = false
  prom-read-auth-enabled = true

[monitor]
  store-enabled = false
